### ISSUE TITLE
Stuck on checking for tris without collisions 

### ISSUE THREAD

**Issue by DKRacingFan** [oohnahleevay/Banjo-Kazooie-Floor-Tool#3]
I chose the SM - Spiral Mountain A file and I got stuck on this step. Not sure if any others are broken like this but some of the other level model files work fine (like Treasure Trove Cove) 
![stuck](https://github.com/oohnahleevay/Banjo-Kazooie-Floor-Tool/assets/57995082/b36d1be9-9a1b-46f9-999e-c535b010f99a)

**Comment by oohnahleevay** [comment]
That means it probably ran into a command in the geometry layout section that I didn't run into in the files I tested with. I'll have it fixed soon.

**Comment by DKRacingFan** [comment]
> That means it probably ran into a command in the geometry layout section that I didn't run into in the files I tested with. I'll have it fixed soon.

The new update fixed it.
